version: "3.6"
services:
  server:
    build:
      context: .
    # FIXME set ports
    ports:
      - 8080:8080
      - 8888:8888
    environment:
      HOST: 0.0.0.0
      HTTP_PORT: 8080
    restart: always
