version: "3.6"
services:
  server:
    image: docker pull ghcr.io/openthingsio/openthings-framework-request-proxy:release
    ports:
      - 8080:8080
      - 3000:3000
    environment:
      HOST: 0.0.0.0
      WEBSOCKET_PORT: 8080
      HTTP_PORT: 3000
      AUTHENTICATION_PLUGIN: EnvironmentVariableAuthenticationPlugin
      DEVICE_KEYS:
    restart: unless-stopped
